googleapis/java-pubsub

- README.md
> Updating README file to fix Issue #11

- google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
> chore: Fix error message in MessageDispatcher.

- samples/snippets/src/main/java/pubsub/PublishWithBatchSettingsExample.java
- samples/snippets/src/main/java/pubsub/PublisherExample.java
- samples/snippets/src/test/java/pubsub/PublisherIT.java
Quickstart publish sample will show up [here](https://cloud.google.com/pubsub/docs/quickstart-client-libraries).
> samples: add quickstart publish sample

- google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
We have sendTestMessage yet, there's still a test that does
not use this method.
Fixes #276 ☕️
> test: Reuse method to publish a message in PublisherImplTest

- samples/snippets/src/main/java/pubsub/CreateSubscriptionWithDeadLetterPolicyExample.java
- samples/snippets/src/main/java/pubsub/CreateSubscriptionWithOrdering.java
- samples/snippets/src/main/java/pubsub/PublishWithOrderingKeys.java
- samples/snippets/src/main/java/pubsub/ResumePublishWithOrderingKeys.java
- samples/snippets/src/test/java/pubsub/AdminIT.java
- samples/snippets/src/test/java/pubsub/PublisherIT.java
Add samples for publish with ordering keys. The test can't be run yet because the feature isn't released.
> samples: publish with ordering keys

- samples/snippets/src/main/java/pubsub/PublishWithOrderingKeys.java
Add a comment to describe best practice.
> samples: add a comment to regional endpoint

- samples/snippets/src/test/java/pubsub/AdminIT.java
> samples: fix lint

- samples/snippets/src/main/java/pubsub/CreateTopicExample.java
- samples/snippets/src/main/java/pubsub/PublisherExample.java
> samples: add a region tag for docs

- google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
> fix: `setParallelPullCount` documentation

- samples/snippets/pom.xml
This will be reflected on https://cloud.google.com/pubsub/docs/quickstart-client-libraries#install
> samples: fix region tags and remove version in pom

- .github/workflows/ci.yaml
> ci: setup workflows for new release branch

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> build: configure branch 1.111.0-sp as a release branch

- google-cloud-pubsub-bom/pom.xml
- pom.xml
chore: move to google sonatype endpoint
> deps: upgrade to a gson version without a vulnerability

- .github/CODEOWNERS
This will allow folks from both the following groups to review changes made to the samples dir. 
- https://github.com/orgs/GoogleCloudPlatform/teams/api-pubsub-and-pubsublite/members
- https://github.com/orgs/googleapis/teams/api-pubsub/members
> chore: additional sample reviewers

- samples/native-image-sample/pom.xml
Tested locally with `mvn package -Pnative` and `mvn test -Pnative`
> docs(sample): remove unused native-image-support dependency

- .github/release-please.yml
- .github/sync-repo-settings.yaml
- README.md
> feat: creating java backport

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 1.118.0

- .github/workflows/ci.yaml
> feat: configure the protected branch

- samples/snippets/src/main/java/pubsub/PublishWithGrpcCompressionExample.java
Forgot to add region tag in #1131
> samples: region tag pubsub_publisher_with_compression

- samples/native-image-sample/README.md
> docs(sample): clean up README of native image sample

- README.md
- google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
> fix: Updated log level from WARNING -> INFO for EOD failures

- versions.txt
#1344 didn't fix #1343 completely somehow. Trying to fix this versions.txt as well.
> chore: fixing sp.1 version in 1.117.x branch

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 1.122.0

- google-cloud-pubsub/pom.xml
- google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
- google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Adding Open Telemetry dependencies to project and publisher
> feat: adding open telemetry dependencies

- google-cloud-pubsub/pom.xml
- google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
- google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/PubsubMessageWrapper.java
- google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
- google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PubsubMessageWrapperTest.java
Adding PubsubMessageWrapper to tie PubsubMessage and Open Telemetry spans together.
Also added framework for parameterized unit tests: https://github.com/google/TestParameterInjector
> feat: Adding Pubsub Message Wrapper

- README.md
- google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
> fix: Fixing the shutdown logic for streaming subscriber connection

- .github/.OwlBot.yaml
- README.md
> chore: preserve MessageDataMatcher from being deleted by owl bot

- .github/sync-repo-settings.yaml
- README.md
The "Kokoro - Against Pub/Sub Lite samples" has been failing for a while. Hannah is investigating the failure. In the meantime, let's unblock other pull requests and add it back to the required checks once the underlying the problem is resolved.
> chore: removing Kokoro - Against Pub/Sub Lite samples from required checks

- .github/blunderbuss.yml
- README.md
Changes the blunderbuss configs so that issues and PRs will now be assigned to me (@michaelpri10)
> chore: change assignees for issues and PRs to michaelpri10

- .cloudbuild/samples_build.yaml
Preparing the sample build via a new CloudBuild set up.
> ci: prepare sample build in CloudBuild

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 1.126.0

- README.md
- samples/snippets/src/main/java/pubsub/SetSubscriptionPolicyExample.java
- samples/snippets/src/main/java/pubsub/SetTopicPolicyExample.java
This updates the member in the Binding for SetTopicPolicyExample and SetSubscriptionPolicyExample to fix a failure in the AdminIT test for the GCP project used for testing.
> test: Change policy member in SetPolicy examples

- README.md
- samples/snippets/src/main/java/pubsub/CreateTopicWithKinesisIngestionExample.java
- samples/snippets/src/main/java/pubsub/UpdateTopicTypeExample.java
- samples/snippets/src/test/java/pubsub/AdminIT.java
Adds a CreateTopicWithKinesisIngestion and UpdateTopicType samples and adds them to the AdminIT test
> docs: Add Kinesis ingestion samples

- .github/workflows/hermetic_library_generation.yaml
Thanks to @diogoteles08 for the inspection on our repos. This PR inlines environment variables to avoid overriding script injections.
> chore: secure hermetic_library_generation workflow

- samples/snippets/src/main/java/pubsub/CreateTopicWithAwsMskIngestionExample.java
- samples/snippets/src/main/java/pubsub/CreateTopicWithAzureEventHubsIngestionExample.java
- samples/snippets/src/main/java/pubsub/CreateTopicWithConfluentCloudIngestionExample.java
- samples/snippets/src/test/java/pubsub/AdminIT.java
> docs: Add samples and tests for ingestion from Kafka sources

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 1.138.0

- .github/CODEOWNERS
b/379670583
With this change, the Java team (release managers) will be able to merge the auto-generated pull requests such as https://github.com/googleapis/java-pubsub/pull/2370. The api-pubsub team can continue to be able to approve such changes.
Here is the list of files modified by the automation recently:
```
suztomo@suztomo2:~/java-pubsub$ git log --author=cloud-java-bot --name-status -100 -- google-cloud-pubsub |grep ".java$" |sort -u
M	google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/package-info.java
M	google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceClient.java
M	google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SchemaServiceSettings.java
M	google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/stub/GrpcPublisherCallableFactory …
```
> ci: the java team to merge auto-generated PRs

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 1.141.0

- .github/scripts/update_generation_config.sh
- .github/workflows/update_generation_config.yaml
- .kokoro/presubmit/graalvm-native-a.cfg
- .kokoro/presubmit/graalvm-native-b.cfg
- .kokoro/presubmit/graalvm-native-c.cfg
- generation_config.yaml
BEGIN_COMMIT_OVERRIDE
BEGIN_NESTED_COMMIT
fix(deps): update the Java code generator (gapic-generator-java) to 2.60.1
END_NESTED_COMMIT
END_COMMIT_OVERRIDE
> chore: update generator config to 2.60.1
