googleapis/java-pubsub

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakePublisherServiceImpl.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
Ensure that the last batch for an ordering key gets published.
=> fix: ordering keys publishing of last batch

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
=> feat: Add flow control support to publisher

synth.py
This PR migrates only synth.py but does not commit the regenerated files. The generation was tested and it works, the updated files are not commited due to breaking changes not related to bazel migration.
**This PR should be pushed after the an already open PR with the braking changes: https://github.com/googleapis/java-pubsub/pull/113**
=> chore: Migrate pubsub synth.py to bazel

grpc-google-cloud-pubsub-v1/clirr-ignored-differences.xml, grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/PublisherGrpc.java, grpc-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/SubscriberGrpc.java
This is the isolated regeneration of the "breaking" grpc stub output from the protoc-grpc plugin update from 1.10.0 to 1.28.0. It removes a `@Deprecated`, `@ExperimentalApi` constant that was deprecated for over 2 years.
This should allow future autogenerated PRs for this client to only contain those changes.
=> chore(regen): isolate gRPC change

.kokoro/continuous/java11-samples.cfg, .kokoro/continuous/jave8-samples.cfg, .kokoro/nightly/java11-samples.cfg, .kokoro/nightly/jave8-samples.cfg, .kokoro/presubmit/java11-samples.cfg, .kokoro/presubmit/jave8-samples.cfg, .kokoro/run_samples_tests.sh, google-cloud-pubsub-bom/pom.xml, pom.xml
Modified these files to set up samples testing. A follow-up PR (#197) will add samples & tests.
```
new file:   .kokoro/continuous/java11-samples.cfg
new file:   .kokoro/continuous/jave8-samples.cfg
new file:   .kokoro/nightly/java11-samples.cfg
new file:   .kokoro/nightly/jave8-samples.cfg
new file:   .kokoro/presubmit/java11-samples.cfg
new file:   .kokoro/presubmit/jave8-samples.cfg
new file:   .kokoro/run_samples_tests.sh
modified:   pom.xml
```
=> feat: set up repo for samples

pom.xml
grpc-iam-v1 added in shared-deps v0.6.0
=> deps: remove grpc test dep since it's now in shared-deps

.gitignore, google-cloud-pubsub/pom.xml, grpc-google-cloud-pubsub-v1/pom.xml, pom.xml, proto-google-cloud-pubsub-v1/pom.xml
=> feat(deps): adopt flatten plugin and google-cloud-shared-dependencies

google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/it/ITPubSubTest.java
Since we have several deprecated method in the ITPubSubTest,
I think we can begin to migrate it to non-deprecated method one.
Fixes #278 ☕️
=> test: Replace deprecated method with non-deprecated one

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
HeaderProvider is missing from PublisherStubSettings initialisation
=> add header providers to PublisherStubSettings

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeSubscriberServiceImpl.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
=> feat: make the stream ack deadline congruent with maxDurationPerAckExtension

samples/snippets/pom.xml
Really odd. #527 actually messed up the README:
=> samples: allow only one pair of region tags

synth.py
This is to prevent synth from proposing PRs like #533. The synth-proposed change will cause the samples checkstyle test to miss this file https://github.com/googleapis/java-pubsub/blob/master/samples/checkstyle-suppressions.xml and therefore fail the checkstyle test. 
The checkstyle exclusions are for classes generated by Avro tools and protoc. They don't comply to the strict checkstyle rules.
- https://github.com/googleapis/java-pubsub/blob/master/samples/snippets/src/main/java/utilities/State.java
- https://github.com/googleapis/java-pubsub/blob/master/samples/snippets/src/main/java/utilities/StateProto.java
=> samples: update synth.py to exclude samples.yaml

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
It looks like we had 60 second deadline extensions in the client before we attempt to update this property, on the premise that it would be updated inline. Due to code drift, this is no longer true, so I changed it to 10s (the min value) by default instead for messages which arrive before the first recalculation cycle.
=> fix: update MessageDispatcher to not extend deadlines of messages which arrive early to 60s

samples/snippets/src/test/java/pubsub/DeadLetterQueueIT.java
=> samples(test): add retry rule in tests

.github/sync-repo-settings.yaml, .kokoro/build.sh, .kokoro/presubmit/presubmit-against-pubsublite-samples.cfg, synth.py
Add a presubmit test to run against samples in https://github.com/googleapis/java-pubsublite.
This is to prevent future development here from breaking `java-pubsublite` unknowingly, which has happened before for `python-pubsub==2.4.0`. See https://pypi.org/project/google-cloud-pubsub/#history
~Need to wait for~ internal cl/378963191 ~to merge first.~ submitted.
--- 
This samples tests should correctly use the local/snapshot artifact instead of the remote one because `mvn clean install` runs before any samples tests.
"Downloading in Maven is triggered by a project declaring a dependency that is not present in the local repository": https://maven.apache.org/guides/introduction/introduction-to-repositories.html#downloading-from-a-remote-repository
=> test: presubmit against Lite samples

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
=> fix: allow retries for subscriber unary rpcs

samples/snippets/src/main/java/pubsub/PublishWithFlowControlExample.java, samples/snippets/src/test/java/pubsub/PublisherIT.java
=> samples: add publish with flow control sample

google-cloud-pubsub-bom/pom.xml
All java client libraries inherit the distributionManagement section form shared-config. To prevent individual pom files from overriding the shared-config version of distributionManagement, it is being removed.
=> chore: remove distributionManagement section

samples/README.md
=> docs(samples): add readme

samples/snippets/src/test/java/pubsub/DeadLetterQueueIT.java, samples/snippets/src/test/java/pubsub/SchemaIT.java
Resetting the resource IDs in samples integration tests before retrying the test. Otherwise, the retry will automatically fail because the resource already exists.
Fixes #742 ☕️
Fixes #731 ☕️
=> fix: reset resource ids before integration test retries

google-cloud-pubsub-bom/pom.xml, pom.xml
This PR updates shared-config to 0.11.0, to publish to google specific endpoint on sonatype.
=> deps: update google-cloud-shared-config to 0.11.0

samples/snippets/src/main/java/pubsub/PublishWithOrderingKeys.java, samples/snippets/src/main/java/pubsub/ResumePublishWithOrderingKeys.java
A `LinkedHashMap` will ensure that messages are processed in order with no ambiguity. 
Samples Snapshot may fail due to recent removal of `SubscriptionPath`. It should be fixed when #907 is reversed.
=> samples: use LinkedHashMap for ordered publish

samples/snippets/src/main/java/pubsub/SubscribeSyncExample.java, samples/snippets/src/main/java/pubsub/SubscribeSyncWithLeaseExample.java
Fixes #189 
The current samples will fail with `io.grpc.StatusRuntimeException: INVALID_ARGUMENT: You have not specified an ack ID in the request` if no messages are returned. Updating them to handle this case. 
This does not affect the existing tests for the samples.
I also noticed something that should not have been published with one of the samples in the first place - my project and topic ID. Apologies.
=> samples: exit early if no messages are returned

samples/snippets/src/main/java/pubsub/PublishWithBatchSettingsExample.java
Matching defaults in sample comments with real defaults in the client library. 
https://github.com/googleapis/java-pubsub/blob/3709b2eb842ac014203680c1af5b081c7a952e2f/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L657-L659
https://github.com/googleapis/java-pubsub/blob/3709b2eb842ac014203680c1af5b081c7a952e2f/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L666-L674
=> samples: DEFAULT_REQUEST_BYTES_THRESHOLD default

samples/native-image-sample/pom.xml
The native image sample is failing during the nightly build with the following error:
```
ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] javac: invalid target release: 11
Usage: javac <options> <source files>
use -help for a list of possible options
```
This is because the Kokoro job uses Java 8. Setting the compiler Java version of the sample to Java 8 should be able to address this issue.
=> docs(sample): use Java 8 for native image sample

README.md, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Removed `BetaApi` annotation for ordering keys.
Fixes #1093  ☕️
=> fix: removed beta api annotation for ordering keys

README.md, pom.xml
The shared dependencies BOM has error_prone_annotations entry. Let's use it rather than declaring the version here.
=> deps: error_prone_annotations from the shared deps BOM

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumerWithResponse.java
Adding BetaApi annotation on AckReplyConsumerWithResponse for Exactly Once Delivery.
Fixes #1049 ☕️
=> fix: adding BetaApi annotation for Exactly Once Delivery

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnectionTest.java
Modack batching fix for LTS 1.117,x
* Moved the `ackIdsInRequest` for modack operations to the correct place. 
* Wrote tests around expected batching/partition behavior to verify change works as expected
Fixes #1126 which was due to incorrect partitioning of `ackIds` for `ModifyAckDeadlineRequest`
=> fix: updated modack batching behavior

README.md, google-cloud-pubsub/clirr-ignored-differences.xml, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumerWithResponse.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumerWithResponseImpl.java
Updating the return types of the `AckReplyConsumerWithResponse` interface, as well as the implementation `AckReplyConsumerWithResponseImpl`, from `Future` to `ApiFuture`, in order to be consistent with the return type of `Publish.publish`.
=> fix: updating return types of ack/nack futures to be consistent with publish

google-cloud-pubsub/pom.xml
Change the scope of the following dependencies to runtime from test
* io.grpc:grpc-stub
* io.grpc:grpc-core
* com.google.http-client:google-http-client
=> fix: fix dependency declaration to properly include runtime scope

README.md, google-cloud-pubsub/clirr-ignored-differences.xml
Removing outdated clirr-ignored-differences content. Keeping the file in place for ease of use in the future.
=> chore: removed outdated clirr-ignored-differences content

.github/release-please.yml
https://github.com/googleapis/java-pubsub/pull/1343 shows "-sp.2" suffix as version. It's an old style "java-lts" configuration. 
The branch: "1.111.0-sp" is ok to continue to use the old style as the branch name suggests.
=> chore: configure 1.117.x branch as java-backport

README.md, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
Adding an explicit check to prevent a publish attempt with no messages.
=> fix: adding an explicit check to prevent empty publishes

pom.xml
Fixes https://github.com/googleapis/java-pubsub/issues/1387, where the build failed:
```
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for io.opencensus:opencensus-api:0.24.0 paths to dependency are:
+-com.google.cloud:google-cloud-pubsub:1.111.0-sp.3
+-io.opencensus:opencensus-api:0.24.0
and
+-com.google.cloud:google-cloud-pubsub:1.111.0-sp.3
+-com.google.api:gax:1.60.1
+-io.opencensus:opencensus-api:0.24.0 (managed) <-- io.opencensus:opencensus-api:0.28.0
and
+-com.google.cloud:google-cloud-pubsub:1.111.0-sp.3
+-com.google.http-client:google-http-client:1.38.0
+-io.opencensus:opencensus-api:0.24.0 (managed) <-- …
```
=> chore: skip opencensus-api enforcer rule (1.111.0-sp branch)

.kokoro/build.sh
Recently discovered that the build script changes were excluded from https://github.com/googleapis/java-pubsub/pull/878. Fortunately, these tests have been regularly tested to verify native image compatibility but the changes in this PR need to be merged to ensure that nothing slips through the cracks in the future.
=> chore: restore missing native image configuration

.github/release-please.yml, .github/sync-repo-settings.yaml
enable releases
```
release-brancher create-pull-request \
--branch-name="1.123.x" \
--target-tag="v1.123.18" \
--repo="googleapis/java-pubsub" \
--pull-request-title="feat: setup 1.123.x lts branch" \
--release-type=java-backport
```
* This branch has been created based on 1.123.18, not 1.123.20 due to incompatible dependencies in 19+
* 'feat' commit ensures next release is 1.124.0
=> feat: setup 1.123.x lts branch

pom.xml
The maven-javadoc-plugin version is defined in the shared config pom.xml.
https://github.com/googleapis/java-shared-config/blob/778a547a09de71dbf9e5a42b155f12d15c319864/pom.xml#L472
The removal of the 4 lines corresponds to the lines touched by the recent RenovateBot:
https://github.com/googleapis/java-pubsub/pull/1733
Parent issue: https://github.com/googleapis/java-shared-config/issues/673
=> build: do not declare javadoc plugin version

.github/sync-repo-settings.yaml, README.md, samples/snippets/src/main/java/pubsub/CreateUnwrappedPushSubscriptionExample.java
=> docs: renaming the CreateUnwrappedPushSubscription File

README.md, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
When a lot of messages are published, then there is a concurrent modification issue in subscriber callbacks for exactly once. This PR makes the outstandingReciepts a concurrentHashMap, and thus allowing us to remove the synchronized keyword from notifyAckSuccess, and fail because all other data structures in this function are concurrent.
I have tested this as described in the following issue, and am unable to see the modification errors.
Fixes #1778
=> fix: concurrent modification of processing receievd messages

.github/workflows/unmanaged_dependency_check.yaml, README.md
@michaelpri10  This is is the implementation for the one I got your review in
go/cloud-sdk-java-dependency-governance-design. This check will
avoid accidentally adding a third-party dependency.
b/320677249
=> ci: unmanaged dependency check

.kokoro/presubmit/graalvm-native-17.cfg, .kokoro/presubmit/graalvm-native.cfg, owlbot.py, pom.xml
Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platform-java-config` is on Maven Central in https://github.com/googleapis/java-pubsub/pull/1884
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290
=> chore: use sdk-platform-java-config to consolidate build configs

.cloudbuild/samples_build.yaml, README.md
Enhancing the sample_build.yaml gradually. Current status:
- AdminIT failed
- DeadLetterQueueIT succeeded
- PublisherIT succeeded
- SchemaIT succeeded
- SubscriberIT succeeded
Merging this for now as this has good progress itself. We'll address AdminIT in a subsequent pull request.
=> ci: setting up samples_build.yaml (2)

google-cloud-pubsub/pom.xml, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckRequestData.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/ModackRequestData.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/OpenTelemetryUtil.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/PubsubMessageWrapper.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/OpenTelemetryTest.java
=> Opentelemetry subscribe

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: setup 1.129.x lts branch

google-cloud-pubsub-bom/pom.xml
Missed updating this POM in https://github.com/googleapis/java-pubsub/pull/1895
Closes https://github.com/googleapis/java-pubsub/pull/2138
=> chore: use sdk-platform-java-config instead of java-shared-config

samples/checkstyle-suppressions.xml
Newly generated StateProto.java file is causing checkstyle to fail. This was autogenerated in #2068.
=> samples: Add style check supressions for generated StateProto.java file

.github/workflows/samples.yaml
=> build: Update samples to use Java 11

google-cloud-pubsub/pom.xml, samples/snippets/src/main/java/pubsub/UsePubSubEmulatorExample.java
=> docs: Update emulator sample to create a topic and publish to it

samples/snippets/src/main/java/pubsub/CreateTopicWithCloudStorageIngestionExample.java, samples/snippets/src/test/java/pubsub/AdminIT.java
This adds a sample and a test for creating an ingestion from GCS topic.
=> docs: Add ingestion from GCS sample

google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java, samples/snippets/src/test/java/pubsub/AdminIT.java, samples/snippets/src/test/java/pubsub/SubscriberIT.java
Fixes a flaky test for the EOD subscription sample. Currently, the test creates and deletes subscriptions before and after every test, but I believe this is causing flaky results. This only runs setUp and tearDown before and after the whole test suite.
This also fixes the GCS ingestion topic, by ensuring the minimum object create time is properly found in the topic definition.
Lastly, this fixes a flaky OpenTelemetry test by ensuring that the publisher is shutdown and all spans are ended.
=> test: Fix flaky tests

google-cloud-pubsub/clirr-ignored-differences.xml, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakePublisherServiceImpl.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeScheduledExecutorService.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnectionTest.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
This PR introduces `java.time` alternatives to existing `org.threeten.bp.*` methods, as well as switching internal variables (if any) to `java.time`
The main constraint is to keep the changes backwards compatible, so for each existing threeten method "`method1(org.threeten.bp.Duration)`" we will add an alternative with a _Duration_ (or _Timestamp_ when applicable) suffix: "`method1Duration(java.time.Duration)`".
For most cases, the implementation will be held in the `java.time` method and the old threeten method will just delegate the call to it. However, for the case of abstract classes, the implementation will be kept in the threeten method to avoid breaking changes (i.e. users that already overloaded the method in their user code).
=> feat: introduce `java.time` variables and methods

samples/README.md
Fixes typo in the repository URL in the samples README.
=> docs: Fix repository URL in samples README

google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/PubsubMessageWrapper.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StatusUtil.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnectionTest.java
This adds retries on ack and modack operations when the failure does not have a metadata map. This also adds a small change to only check ack IDs that are in a specific modack batch and adds a StatusUtil helper method. Additionally, we will forget ack IDs when an ack or modack fails with a non-retryable error.
=> fix: Add retries for ack and modack operations that don't return with a metadata map

samples/snippets/src/main/java/pubsub/SubscribeWithErrorListenerExample.java, samples/snippets/src/main/java/pubsub/SubscribeWithExactlyOnceConsumerWithResponseExample.java
- Update the subscribe with error listener to not recreate the subscriber client on unrecoverable failures.
- Update the subscribe with exactly-once sample to use a locational endpoint
=> docs(sample): Update the subscribe with error listener and subscribe with exactly-once samples

.github/scripts/update_generation_config.sh, .github/workflows/update_generation_config.yaml, README.md
Unfortunately, https://github.com/googleapis/sdk-platform-java/pull/3853 cannot be automatically propagated. 
This PR manually updates this script with the latest.
Confirmation in https://github.com/googleapis/java-pubsub/actions/runs/16504769851
=> chore: manual update of update_generation_config.sh

google-cloud-pubsub/clirr-ignored-differences.xml, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java, google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java, google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnectionTest.java
Avoids the use of an additional executor to give users more control over their executors and number of threads. This is an update to PR #2505.
Fixes #2480
=> fix: Use the system executor instead of a separate thread pool for EOD ack/modack callbacks
